#!/usr/bin/env python3
"""Emit docs/jurix/numbers.tex: one \\newcommand per number the paper
cites, computed from the results files. The LaTeX source uses the macros
and never contains a typed number, so a re-score changes the paper by
re-running this script. Macro names are letters only (LaTeX rule)."""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
R = HERE / "results"
OUT = HERE / "docs" / "jurix" / "numbers.tex"

full = json.loads((R / "rescore_full.json").read_text())
loops = json.loads((R / "rescore_loops.json").read_text())
gee = json.loads((R / "stats_gee.json").read_text())
human = json.loads((R / "human_baseline.json").read_text())["aggregates"]["overall"]
pins = json.loads((R / "pincites.json").read_text())
decomp = json.loads((R / "notincorpus_decomposition.json").read_text())

ALPHA = {"qwen30b": "Qwen", "mistralsmall": "Mistral", "llama4mav": "Llama",
         "deepseek": "Deepseek", "gpt54mini": "Gpt", "sonnet": "Sonnet",
         "grok43": "Grok"}
CONDS = {"baseline": "Base", "quota": "Quota", "temporal": "Temporal",
         "stakes": "Stakes", "combo": "Combo"}

lines = ["% generated by src/emit_macros.py; do not edit by hand"]


def emit(name, value):
    lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")


def fmt3(x):
    return f"{x:.3f}"


for m, mk in ALPHA.items():
    for c, ck in CONDS.items():
        cell = full[m][c]
        emit(f"exist{mk}{ck}", fmt3(cell["existence_rate"]))
        emit(f"strict{mk}{ck}", fmt3(cell["strict_rate"]))
        if cell["tchecked"]:
            emit(f"viol{mk}{ck}", f"{100 * cell['viol'] / cell['tchecked']:.0f}")
    for arm, ak in (("true", "True"), ("scrambled", "Scr"), ("none", "None"), ("half", "Half"), ("quarter", "Quarter"), ("threequarter", "Threeq")):
        sub = [r for r in loops[m] if r["arm"] == arm]
        if not sub:
            continue
        f0 = [r["r0"]["strict"] for r in sub if r["r0"]["strict"] is not None]
        f1 = [r["final"]["strict"] for r in sub if r["final"]["strict"] is not None]
        emit(f"loop{mk}{ak}Start", fmt3(sum(f0) / len(f0)))
        emit(f"loop{mk}{ak}Final", fmt3(sum(f1) / len(f1)))
        emit(f"conv{mk}{ak}", str(sum(r["converged"] for r in sub)))
    emit(f"tempOnlyChecked{mk}", str(full[m]["temporal"]["tchecked"]))
    emit(f"tempOnlyViol{mk}", str(full[m]["temporal"]["viol"]))
    tc = full[m]["temporal"]["tchecked"] + full[m]["combo"]["tchecked"]
    emit(f"tempChecked{mk}", str(tc))
    emit(f"tempViol{mk}", str(full[m]["temporal"]["viol"] + full[m]["combo"]["viol"]))
    tr = [r for r in loops[m] if r["arm"] == "true"]
    emit(f"cleanRZero{mk}", str(sum(1 for r in tr if r["converged"] and r["rounds"] == 1)))
    for kind, kk in (("citation", "Cite"), ("quote", "Quote")):
        for c, ck in CONDS.items():
            if c == "baseline":
                continue
            g = gee.get(f"{kind}:{m}:{c}")
            if g:
                emit(f"or{kk}{mk}{ck}", f"{g['OR']:.2f}")
                if "ci_low" in g:
                    emit(f"ci{kk}{mk}{ck}", f"{g['ci_low']:.2f} to {g['ci_high']:.2f}")
                emit(f"p{kk}{mk}{ck}", f"{g['p']:.4f}" if g["p"] >= 0.0001 else "<0.0001")
                emit(f"sig{kk}{mk}{ck}", "*" if g["p"] < 0.05 else "")
    p = pins.get(m)
    if p:
        tot = p["quote_at_pin"] + p["quote_near_pin"] + p["quote_not_at_pin"]
        if tot:
            emit(f"pinAt{mk}", f"{100 * p['quote_at_pin'] / tot:.0f}")
            emit(f"pinWrong{mk}", f"{100 * p['quote_not_at_pin'] / tot:.0f}")

emit("pinOutTotal", str(sum(v["pin_out_of_span"] for k, v in pins.items() if k in ALPHA)))
emit("pinInTotal", f"{sum(v['pin_in_span'] for k, v in pins.items() if k in ALPHA):,}")
ph = pins.get("human")
if ph:
    tot = ph["quote_at_pin"] + ph["quote_near_pin"] + ph["quote_not_at_pin"]
    emit("pinAtHuman", f"{100 * ph['quote_at_pin'] / tot:.0f}")
    emit("pinHumanN", str(tot))
emit("cleanRZeroTotal", str(sum(1 for m in ALPHA for r in loops[m] if r["arm"] == "true" and r["converged"] and r["rounds"] == 1)))
emit("humanStrict", fmt3(human["strict_quote_rate"]))
emit("humanScored", str(human["n_quotes_scored"]))
emit("humanExist", fmt3(human["existence_rate"]))
emit("humanExcerpts", str(human["n_excerpts"]))
emit("nModels", str(len(ALPHA)))
emit("nDrafts", f"{48 * 5 * len(ALPHA):,}")
emit("nEpisodes", f"{48 * len(ALPHA)}")
emit("sonnetParaphrase", str(decomp["sonnet"]["paraphrase_in_quotes"]))
emit("sonnetFabricated", str(decomp["sonnet"]["fabricated_language"]))
emit("sonnetOutOfScope", str(decomp["sonnet"]["out_of_scope_non_us"]))
s = decomp["sonnet"]
emit("sonnetParaphrasePct",
     f"{100 * s['paraphrase_in_quotes'] / (s['paraphrase_in_quotes'] + s['fabricated_language'] + s['out_of_scope_non_us']):.0f}")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"{len(lines) - 1} macros -> {OUT}")

# ---- revision additions (all optional: skip if the artifact is absent) ----
extra = []


def emit2(name, value):
    extra.append(f"\\newcommand{{\\{name}}}{{{value}}}")


rs_path = R / "revision_stats.json"
if rs_path.exists():
    rs = json.loads(rs_path.read_text())
    emit2("nPressured", f"{rs['n_pressured_drafts']:,}")
    emit2("nHolmTests", str(next(iter(rs["holm"].values()))["n_tests"]))
    emit2("humanLenient", f"{rs['human_lenient']:.3f}")
    emit2("humanNearMissShare", f"{100 * rs['human_near_miss_share']:.0f}")
    for key, v in rs["holm"].items():
        kind, m, c = key.split(":")
        mk = ALPHA.get(m)
        if mk:
            kk = "Cite" if kind == "citation" else "Quote"
            emit2(f"holm{kk}{mk}{CONDS[c]}", f"{v['holm_p']:.3f}" if v["holm_p"] >= 0.001 else "<0.001")
    for cell, v in rs["cells"].items():
        m, c = cell.split(":")
        mk = ALPHA.get(m)
        if mk and v.get("lenient") is not None:
            emit2(f"lenient{mk}{CONDS[c]}", f"{v['lenient']:.3f}")
    for key, v in rs["loop_counts"].items():
        m, arm = key.split(":")
        mk = ALPHA.get(m)
        ak = {"true": "True", "scrambled": "Scr", "none": "None", "half": "Half", "quarter": "Quarter", "threequarter": "Threeq"}.get(arm)
        if mk and ak:
            emit2(f"lqScored{mk}{ak}Start", str(v["quotes_scored_r0"]))
            emit2(f"lqScored{mk}{ak}Final", str(v["quotes_scored_final"]))
            emit2(f"lqAcc{mk}{ak}Start", str(v["accurate_r0"]))
            emit2(f"lqAcc{mk}{ak}Final", str(v["accurate_final"]))
            emit2(f"lCites{mk}{ak}Start", str(v["cites_r0"]))
            emit2(f"lCites{mk}{ak}Final", str(v["cites_final"]))
            if v.get("exist_r0") == v.get("exist_r0"):
                emit2(f"lExist{mk}{ak}Start", fmt3(v["exist_r0"]))
                emit2(f"lExist{mk}{ak}Final", fmt3(v["exist_final"]))
    for key, v in rs.get("loop_tests", {}).items():
        m, contrast = key.split(":")
        mk = ALPHA.get(m)
        ck = {"true_vs_scrambled": "Scr", "true_vs_none": "None", "true_vs_half": "Half"}[contrast]
        if mk:
            emit2(f"ldiff{mk}{ck}", f"{v['mean_diff']:.2f}")
            emit2(f"lci{mk}{ck}", f"{v['ci_low']:.2f} to {v['ci_high']:.2f}")
            emit2(f"lp{mk}{ck}", f"{v['wilcoxon_p']:.3f}" if v["wilcoxon_p"] >= 0.001 else f"{v['wilcoxon_p']:.4f}")
            emit2(f"ln{mk}{ck}", str(v["n_pairs"]))
    emit2("unverifiablePct", f"{rs['unverifiable_share_pct']:.1f}")
    emit2("nCitationRecords", f"{rs['n_citation_records']:,}")
    emit2("sonnetTempChecked", str(rs["sonnet_temporal_checked"]))
    emit2("sonnetTempViol", str(rs["sonnet_temporal_viol"]))
    gm = rs["glm_missing"]
    emit2("glmMissing", str(sum(gm.values())))
    emit2("glmMissingCombo", str(gm["combo"]))
    for key, v in rs["memorization"].items():
        m, c = key.split(":")
        mk = ALPHA.get(m)
        if mk and v["canonical_share"] is not None:
            emit2(f"canon{mk}{CONDS[c]}", f"{100 * v['canonical_share']:.0f}")
    raw = rs["raw_counts"]
    for m, mk in ALPHA.items():
        for c, ck in CONDS.items():
            d = raw.get(f"{m}:{c}:citation", {})
            emit2(f"nf{mk}{ck}", str(d.get("not_found", 0)))
            emit2(f"ex{mk}{ck}", str(d.get("exists", 0)))

pp = R / "paraphrase_comparison.json"
if pp.exists():
    para = json.loads(pp.read_text())
    for m, mk in ALPHA.items():
        if m in para:
            for which, wk in (("original", "Orig"), ("paraphrase", "Para")):
                c = para[m][which].get("combo", {})
                if c.get("exist") is not None:
                    emit2(f"para{wk}Exist{mk}Combo", fmt3(c["exist"]))
                if c.get("strict") is not None:
                    emit2(f"para{wk}Strict{mk}Combo", fmt3(c["strict"]))

gl = R / "full_glm47flash" / "drafts"
if gl.exists():
    emit2("glmDrafts", str(len(list(gl.glob("*.txt")))))

dc = R / "notincorpus_decomposition.json"
if dc.exists():
    d = json.loads(dc.read_text())
    for m, mk in ALPHA.items():
        if m in d:
            x = d[m]
            tot = x["paraphrase_in_quotes"] + x["fabricated_language"] + x["out_of_scope_non_us"]
            emit2(f"decompPara{mk}", str(x["paraphrase_in_quotes"]))
            emit2(f"decompFab{mk}", str(x["fabricated_language"]))
            emit2(f"decompOut{mk}", str(x["out_of_scope_non_us"]))
            if tot:
                emit2(f"decompParaPct{mk}", f"{100 * x['paraphrase_in_quotes'] / tot:.0f}")

pr = R / "provenance_report.md"
if pr.exists():
    import re as _re
    from collections import Counter as _C
    cnt = _C()
    for line in open(pr):
        m_ = _re.match(r"- \*\*(\w+)\*\* \| (\w+) ", line)
        if m_:
            cnt[(m_.group(2), m_.group(1))] += 1
    for m, mk in ALPHA.items():
        if any(k[0] == m for k in cnt):
            emit2(f"misattr{mk}", str(cnt[(m, "misattributed")]))
            emit2(f"falseAlarm{mk}", str(cnt[(m, "found_in_attributed")]))
            emit2(f"notInCorpus{mk}", str(cnt[(m, "not_in_scotus_corpus")]))
            emit2(f"genericMatch{mk}", str(cnt[(m, "generic_phrase_match")]))
    emit2("misattrTotal", str(sum(v for k, v in cnt.items() if k[1] == "misattributed")))
    for m, mk in ALPHA.items():
        tot = sum(v for k, v in cnt.items() if k[0] == m)
        if tot:
            emit2(f"inaccTotal{mk}", str(tot))
            emit2(f"falseAlarmPct{mk}", f"{100 * cnt[(m, 'found_in_attributed')] / tot:.1f}")

rp = R / "replicate.json"
if rp.exists():
    rep = json.loads(rp.read_text())
    sd_e, sd_s, ident, n = [], [], 0, 0
    sign_stable = 0
    for m, mk in ALPHA.items():
        if m not in rep:
            continue
        r = rep[m]
        for c, ck in (("baseline", "Base"), ("combo", "Combo")):
            emit2(f"repMeanExist{mk}{ck}", fmt3(r[c]["exist_mean"]))
            emit2(f"repMeanStrict{mk}{ck}", fmt3(r[c]["strict_mean"]))
            emit2(f"repSdStrict{mk}{ck}", fmt3(r[c]["strict_sd"]))
            sd_e.append(r[c]["exist_sd"]); sd_s.append(r[c]["strict_sd"])
        ident += r["identical_any_pair"]; n += r["n_drafts_per_run"]
        signs = {(r[f"{run}_contrast"]["strict"] or 0) > 0 for run in ("full", "rep2", "rep3")}
        sign_stable += len(signs) == 1
    emit2("repMaxExistSd", fmt3(max(sd_e)))
    emit2("repMaxStrictSd", fmt3(max(sd_s)))
    emit2("repMaxExistRange", fmt3(max(rep[m][c]["exist_range"] for m in ALPHA if m in rep for c in ("baseline", "combo"))))
    emit2("repMaxStrictRange", fmt3(max(rep[m][c]["strict_range"] for m in ALPHA if m in rep for c in ("baseline", "combo"))))
    emit2("repIdentical", str(ident))
    emit2("repDrafts", str(n))
    emit2("repModels", str(len([m for m in ALPHA if m in rep])))
    emit2("repSignStable", str(sign_stable))
    emit2("repMistralIdentical", str(rep.get("mistralsmall", {}).get("identical_any_pair", 0)))

gr = R / "stats_gee_runs.json"
if gr.exists():
    g = json.loads(gr.read_text())
    surv = {"citation": [], "quote": []}
    for k, v in g.items():
        kind, m, _ = k.split(":")
        mk = ALPHA.get(m)
        if not mk:
            continue
        kk = "Cite" if kind == "citation" else "Quote"
        emit2(f"runsOr{kk}{mk}", f"{v['OR']:.2f}")
        emit2(f"runsCi{kk}{mk}", f"{v['ci_low']:.2f} to {v['ci_high']:.2f}")
        emit2(f"runsHolm{kk}{mk}", f"{v['holm_p']:.3f}" if v["holm_p"] >= 0.001 else "$<$0.001")
        if v["holm_p"] < 0.05:
            surv[kind].append(m)
    emit2("runsQuoteSurvivors", str(len(surv["quote"])))
    emit2("runsCiteSurvivors", str(len(surv["citation"])))
    qs = [g[f"quote:{m}:combo"]["OR"] for m in ALPHA if m in {x for x in surv["quote"]} and m != "sonnet"]
    if qs:
        emit2("runsQuoteOrMin", f"{min(qs):.2f}")
        emit2("runsQuoteOrMax", f"{max(qs):.2f}")

ph = R / "phrasing_stats.json"
if ph.exists():
    ps = json.loads(ph.read_text())
    emit2("phrSurvA", str(len(ps["survivors_a"])))
    emit2("phrMaxStrictDiff", f"{100 * ps['max_strict_diff_ab']:.0f}")
    emit2("phrMaxExistDiff", f"{100 * ps['max_exist_diff_ab']:.0f}")
    emit2("phrSurvB", str(len(ps["survivors_b"])))
    emit2("phrAinB", str(len(ps["a_replicated_in_b"])))
    emit2("phrAinPooled", str(len(ps["a_replicated_pooled"])))
    emit2("phrSurvPooled", str(len(ps["survivors_pooled"])))
    qc = [k for k in ps["survivors_pooled"] if k.startswith("quote:") and k.endswith(":combo")]
    emit2("phrPooledQuoteCombo", str(len(qc)))
    ec = [k for k in ps["survivors_pooled"] if k.startswith("citation:")]
    emit2("phrPooledCiteModels", str(len({k.split(":")[1] for k in ec})))
    for key, v in ps["cells_b"].items():
        m, c = key.split(":")
        mk = ALPHA.get(m)
        if mk and c in CONDS:
            if v["exist"] is not None:
                emit2(f"existB{mk}{CONDS[c]}", fmt3(v["exist"]))
            if v["strict"] is not None:
                emit2(f"strictB{mk}{CONDS[c]}", fmt3(v["strict"]))
    for key, v in ps["gee_pooled"].items():
        kind, m, c = key.split(":")
        mk = ALPHA.get(m)
        if mk:
            kk = "Cite" if kind == "citation" else "Quote"
            emit2(f"pooledOr{kk}{mk}{CONDS[c]}", f"{v['OR']:.2f}")
            hp = ps["holm_pooled"][key]
            emit2(f"pooledHolm{kk}{mk}{CONDS[c]}", f"{hp:.3f}" if hp >= 0.001 else "<0.001")
    ors = [ps["gee_pooled"][k]["OR"] for k in qc]
    if ors:
        emit2("phrPooledQuoteOrMin", f"{min(ors):.2f}")
        emit2("phrPooledQuoteOrMax", f"{max(ors):.2f}")

gs = R / "grounded_stats.json"
if gs.exists():
    g = json.loads(gs.read_text())
    rm = R / "retrieval" / "_meta.json"
    if rm.exists():
        emit2("retrievalCorpus", f"{json.loads(rm.read_text())['indexed_opinions']:,}")
    for m, mk in ALPHA.items():
        for c, ck in (("baseline", "Base"), ("combo", "Combo")):
            key = f"{m}:{c}"
            if key in g["grounded"]:
                v = g["grounded"][key]
                emit2(f"gExist{mk}{ck}", fmt3(v["exist"]))
                emit2(f"gStrict{mk}{ck}", fmt3(v["strict"]))
                emit2(f"gNotFound{mk}{ck}", str(v["not_found"]))
        rs = g["retrieved_share"].get(m)
        if rs and rs["share"] is not None:
            emit2(f"gRetrieved{mk}", f"{100 * rs['share']:.0f}")
        dd = g.get("decomposition_grounded", {}).get(m)
        if dd:
            tot = dd["paraphrase_in_quotes"] + dd["fabricated_language"] + dd["out_of_scope_non_us"]
            emit2(f"gInacc{mk}", str(tot))
            emit2(f"gParaPct{mk}", f"{100 * dd['paraphrase_in_quotes'] / tot:.0f}")
    shares = [v["share"] for v in g["retrieved_share"].values() if v["share"] is not None]
    emit2("gRetrievedMin", f"{100 * min(shares):.0f}")
    emit2("gRetrievedMax", f"{100 * max(shares):.0f}")
    nf = sum(g["grounded"][k]["not_found"] for k in g["grounded"])
    adj = sum(g["grounded"][k]["adjudicable"] for k in g["grounded"])
    emit2("gNotFoundTotal", str(nf))
    emit2("gAdjudicableTotal", f"{adj:,}")
    nfc = sum(g["closed"][k]["not_found"] for k in g["closed"])
    adjc = sum(g["closed"][k]["adjudicable"] for k in g["closed"])
    emit2("cNotFoundTotal", str(nfc))
    emit2("cAdjudicableTotal", f"{adjc:,}")
    base_rise = sum(1 for m in ALPHA if f"{m}:baseline" in g["grounded"] and
                    g["grounded"][f"{m}:baseline"]["strict"] > g["closed"][f"{m}:baseline"]["strict"])
    emit2("gBaseStrictRise", str(base_rise))
    emit2("gStrictMax", fmt3(max(v["strict"] for v in g["grounded"].values())))
    for k, v in g["gee"].items():
        kind, m, c = k.split(":")
        mk = ALPHA.get(m)
        if mk and v.get("OR") is not None:
            kk = "Cite" if kind == "citation" else "Quote"
            emit2(f"gOr{kk}{mk}{CONDS[c]}", f"{v['OR']:.1f}" if v["OR"] >= 10 else f"{v['OR']:.2f}")
            emit2(f"gHolm{kk}{mk}{CONDS[c]}", f"{v['holm_p']:.3f}" if v["holm_p"] >= 0.001 else "$<$0.001")
    qs = [k for k, v in g["gee"].items() if k.startswith("quote:") and v.get("holm_p") is not None and v["holm_p"] < 0.05]
    emit2("gQuoteSurvivors", str(len(qs)))
    cs = [k for k, v in g["gee"].items() if k.startswith("citation:") and v.get("holm_p") is not None and v["holm_p"] < 0.05]
    emit2("gCiteSurvivors", str(len(cs)))

ap = R / "appellate_stats.json"
if ap.exists():
    a = json.loads(ap.read_text())
    for m, mk in ALPHA.items():
        for c, ck in (("baseline", "Base"), ("combo", "Combo")):
            v = a["rates"].get(f"{m}:{c}")
            if v:
                emit2(f"aExist{mk}{ck}", fmt3(v["exist"]))
                emit2(f"aStrict{mk}{ck}", fmt3(v["strict"]))
                emit2(f"aNotFound{mk}{ck}", str(v["not_found"]))
                emit2(f"aAdj{mk}{ck}", str(v["adjudicable"]))
        for c, ck in (("quota", "Quota"), ("temporal", "Temporal"), ("stakes", "Stakes"), ("combo", "Combo")):
            v = a["rates"].get(f"{m}:{c}")
            if v and c not in ("baseline", "combo"):
                emit2(f"aExist{mk}{ck}", fmt3(v["exist"]))
                emit2(f"aStrict{mk}{ck}", fmt3(v["strict"]))
            for kind, kk in (("citation", "Cite"), ("quote", "Quote")):
                g = a["gee"].get(f"{kind}:{m}:{c}", {})
                if g.get("OR") is not None:
                    emit2(f"aOr{kk}{mk}{ck}", f"{g['OR']:.2f}")
                    emit2(f"aHolm{kk}{mk}{ck}", f"{g['holm_p']:.3f}" if g["holm_p"] >= 0.001 else "$<$0.001")
                    if c == "combo":
                        emit2(f"aOr{kk}{mk}", f"{g['OR']:.2f}")
                        emit2(f"aHolm{kk}{mk}", f"{g['holm_p']:.3f}")
                g2 = a["gee_pooled_tasks"].get(f"{kind}:{m}:{c}", {})
                if g2.get("OR") is not None:
                    emit2(f"aPooledOr{kk}{mk}{ck}", f"{g2['OR']:.2f}")
                    emit2(f"aPooledHolm{kk}{mk}{ck}", f"{g2['holm_p']:.3f}" if g2["holm_p"] >= 0.001 else "$<$0.001")
                    if c == "combo":
                        emit2(f"aPooledOr{kk}{mk}", f"{g2['OR']:.2f}")
                        emit2(f"aPooledHolm{kk}{mk}", f"{g2['holm_p']:.3f}" if g2["holm_p"] >= 0.001 else "$<$0.001")
        rm = a["reporter_mix"].get(m)
        if rm and rm["us_share"] is not None:
            emit2(f"aUsShare{mk}", f"{100 * rm['us_share']:.0f}")
    pl = a["reporter_mix"].get("_pooled")
    if pl:
        emit2("aNfFederalPct", f"{100 * pl['federal_nf'] / pl['federal']:.0f}")
        emit2("aNfUsPct", f"{100 * pl['us_nf'] / pl['us']:.0f}")
        emit2("aNfOtherShare", f"{100 * pl['other_nf'] / (pl['us_nf'] + pl['federal_nf'] + pl['other_nf']):.0f}")
        emit2("aNfFederal", str(pl["federal_nf"]))
        emit2("aFederalCites", f"{pl['federal']:,}")
    ex = [a["rates"][f"{m}:baseline"]["exist"] for m in ALPHA if f"{m}:baseline" in a["rates"]]
    emit2("aExistBaseMin", fmt3(min(ex)))
    emit2("aExistBaseMax", fmt3(max(ex)))
    us = [a["reporter_mix"][m]["us_share_baseline"] for m in ALPHA if m in a["reporter_mix"] and a["reporter_mix"][m].get("us_share_baseline") is not None]
    for c, ck in (("baseline", "Base"), ("stakes", "Stakes"), ("temporal", "Temporal"), ("combo", "Combo")):
        if c in a.get("sonnet_median_year", {}):
            emit2(f"aSonnetYear{ck}", str(a["sonnet_median_year"][c]))
    emit2("aUsShareMin", f"{100 * min(us):.0f}")
    emit2("aUsShareMax", f"{100 * max(us):.0f}")
    emit2("aShortDrafts", str(sum(v["short_drafts"] for k, v in a["reporter_mix"].items() if not k.startswith("_"))))
    lower = sum(1 for m in ALPHA if f"{m}:baseline" in a["rates"] and
                a["rates"][f"{m}:baseline"]["exist"] < a["baseline_vs_scotus"][m]["scotus_exist"])
    emit2("aLowerThanScotus", str(lower))
    qs = [k for k, v in a["gee_pooled_tasks"].items() if k.startswith("quote:") and v.get("holm_p") is not None and v["holm_p"] < 0.05 and v["OR"] < 1]
    emit2("aPooledQuoteFalls", str(len(qs)))
    surv = [k for k, v in a["gee"].items() if v.get("holm_p") is not None and v["holm_p"] < 0.05]
    emit2("aSurvivors", str(len(surv)))

ea = R / "era_attribution_check.json"
if ea.exists():
    e = json.loads(ea.read_text())
    emit2("eraPreStrict", fmt3(e["era"]["pooled"]["pre1970_strict"]))
    emit2("eraPostStrict", fmt3(e["era"]["pooled"]["post1970_strict"]))
    emit2("eraPreN", str(e["era"]["pooled"]["pre1970_scored"]))
    emit2("eraPostN", f"{e['era']['pooled']['post1970_scored']:,}")
    emit2("misattrSameDraft", str(e["attribution"]["pooled"]["true_source_cited_in_draft"]))
    emit2("misattrSameDraftPct", f"{100 * e['attribution']['pooled']['share']:.0f}")

jc = R / "jury_calibration.json"
if jc.exists():
    j = json.loads(jc.read_text())
    emit2("juryBinary", f"{j['budget_binary']:.3f}")
    emit2("juryThreeway", f"{j['budget_threeway']:.3f}")
    emit2("juryFrontier", f"{j['frontier']:.3f}")
    emit2("juryBar", f"{j['bar']:.2f}")
import sqlite3 as _sq
try:
    from pilot import DB as _DB
    con = _sq.connect(_DB)
    for rep, mk in (("F3d", "IndexFThird"), ("F2d", "IndexFSecond")):
        n = con.execute("SELECT count(*) FROM citations WHERE replace(replace(reporter,' ',''),'.','')=?", (rep,)).fetchone()[0]
        emit2(mk, f"{round(n, -3):,}")
except Exception:
    pass
pv = R / "provenance_six.log"
if pv.exists():
    import re as _re2
    m_ = _re2.findall(r"(\d+) documents indexed", pv.read_text())
    if m_:
        emit2("provenanceCorpus", f"{int(m_[-1]):,}")
if rs_path.exists():
    mem = json.loads(rs_path.read_text())["memorization"]
    emit2("sonnetYearBase", str(mem["sonnet:baseline"]["median_year"]))
    emit2("sonnetYearCombo", str(mem["sonnet:combo"]["median_year"]))
    emit2("sonnetYearStakes", str(mem["sonnet:stakes"]["median_year"]))
cnt3 = {}
for fn in ("records.jsonl", "records_rep2.jsonl", "records_rep3.jsonl"):
    fp = R / fn
    if fp.exists():
        for l in open(fp):
            r = json.loads(l)
            if r["model"] == "sonnet" and r["kind"] == "citation" and r["condition"] in ("baseline", "combo"):
                cnt3[(r["condition"], r["verdict"])] = cnt3.get((r["condition"], r["verdict"]), 0) + 1
if cnt3:
    emit2("sonnetRunsNfBase", str(cnt3.get(("baseline", "not_found"), 0)))
    emit2("sonnetRunsAdjBase", f"{cnt3.get(('baseline', 'exists'), 0) + cnt3.get(('baseline', 'not_found'), 0):,}")
    emit2("sonnetRunsNfCombo", str(cnt3.get(("combo", "not_found"), 0)))
    emit2("sonnetRunsAdjCombo", f"{cnt3.get(('combo', 'exists'), 0) + cnt3.get(('combo', 'not_found'), 0):,}")

lt = R / "loop_transitions.json"
if lt.exists():
    t = json.loads(lt.read_text())
    for m, mk in ALPHA.items():
        if m not in t:
            continue
        c = t[m]
        for arm, ak in (("true", "True"), ("scrambled", "Scr"), ("none", "None"), ("half", "Half"), ("quarter", "Quarter"), ("threequarter", "Threeq")):
            for v0, vk in (("flagged", "Flag"), ("accurate", "Acc")):
                kept_acc = c.get(f"{arm}:{v0}:kept:accurate", 0) + c.get(f"{arm}:{v0}:edited:accurate", 0)
                kept_flag = c.get(f"{arm}:{v0}:kept:flagged", 0) + c.get(f"{arm}:{v0}:edited:flagged", 0)
                emit2(f"tr{ak}{vk}ToAcc{mk}", str(kept_acc))
                emit2(f"tr{ak}{vk}ToFlag{mk}", str(kept_flag))
                if v0 == "flagged":
                    emit2(f"tr{ak}FlagLeft{mk}", str(kept_flag))
                emit2(f"tr{ak}{vk}Dequoted{mk}", str(c.get(f"{arm}:{v0}:dequoted", 0)))
                emit2(f"tr{ak}{vk}Deleted{mk}", str(c.get(f"{arm}:{v0}:deleted", 0)))
            emit2(f"tr{ak}AddedAcc{mk}", str(c.get(f"{arm}:added:accurate", 0)))
            emit2(f"tr{ak}AddedFlag{mk}", str(c.get(f"{arm}:added:flagged", 0)))
            fl = [c.get(f"{arm}:flagged:{k}", 0) for k in
                  ("kept:flagged", "edited:flagged", "kept:accurate", "edited:accurate", "dequoted", "deleted")]
            ac = [c.get(f"{arm}:accurate:{k}", 0) for k in
                  ("kept:accurate", "edited:accurate", "kept:flagged", "edited:flagged", "dequoted", "deleted")]
            if arm == "true":
                emit2(f"trFlagRZero{mk}", str(sum(fl)))
                emit2(f"trAccRZero{mk}", str(sum(ac)))
            emit2(f"tr{ak}AccRemoved{mk}", str(ac[2] + ac[3] + ac[4] + ac[5]))
            emit2(f"tr{ak}FlagRemoved{mk}", str(fl[4] + fl[5]))

# loop citation accounting and lenient rates by arm (src/loop_citations.py)
lc = R / "loop_citations.json"
if lc.exists():
    t = json.loads(lc.read_text())
    tot = {}
    for m, mk in ALPHA.items():
        if m not in t:
            continue
        e = t[m]["existence_trace"]
        for k in ("nf_r0", "nf_removed", "nf_kept", "new_exists", "new"):
            tot[k] = tot.get(k, 0) + e.get(k, 0)
        emit2(f"lcNfRZero{mk}", str(e.get("nf_r0", 0)))
        emit2(f"lcNfRemoved{mk}", str(e.get("nf_removed", 0)))
        emit2(f"lcNfKept{mk}", str(e.get("nf_kept", 0)))
        emit2(f"lcNewExists{mk}", str(e.get("new_exists", 0)))
        for arm, ak in (("true", "True"), ("scrambled", "Scr"), ("none", "None"), ("half", "Half"), ("quarter", "Quarter"), ("threequarter", "Threeq")):
            v = t[m]["final_lenient"].get(arm)
            if v is not None:
                emit2(f"llen{mk}{ak}Final", fmt3(v))
    for k, nk in (("nf_r0", "RZero"), ("nf_removed", "Removed"), ("nf_kept", "Kept"), ("new_exists", "NewExists"), ("new", "New")):
        emit2(f"lcNf{nk}Total", str(tot.get(k, 0)))
    emit2("lcModels", str(len([m for m in ALPHA if m in t])))

# grounded loop (src/loop_arm.py --grounded; rescore_loops.py --prefix gloop; loop_transitions.py --prefix gloop)
gl = R / "gloop_transitions.json"
if gl.exists():
    t = json.loads(gl.read_text())
    for m, mk in ALPHA.items():
        if m not in t:
            continue
        c = t[m]
        fl = [c.get(f"true:flagged:{k}", 0) for k in ("kept:accurate", "edited:accurate", "kept:flagged", "edited:flagged", "deleted", "dequoted")]
        emit2(f"gtrFlagRZero{mk}", str(sum(fl)))
        emit2(f"gtrFlagToAcc{mk}", str(fl[0] + fl[1]))
        emit2(f"gtrFlagLeft{mk}", str(fl[2] + fl[3]))
        emit2(f"gtrFlagDeleted{mk}", str(fl[4]))
        emit2(f"gtrFlagDequoted{mk}", str(fl[5]))
    gr = R / "rescore_gloop.json"
    if gr.exists():
        rows = json.loads(gr.read_text())
        for m, mk in ALPHA.items():
            if m not in rows:
                continue
            sub = [r for r in rows[m] if r["arm"] == "true"]
            s0 = [r["r0"]["strict"] for r in sub if r["r0"]["strict"] is not None]
            s1 = [r["final"]["strict"] for r in sub if r["final"]["strict"] is not None]
            emit2(f"gloop{mk}TrueStart", fmt3(sum(s0) / len(s0)) if s0 else "--")
            emit2(f"gloop{mk}TrueFinal", fmt3(sum(s1) / len(s1)) if s1 else "--")
            emit2(f"gloop{mk}Clean", str(sum(r["converged"] for r in sub)))
            emit2(f"gloop{mk}N", str(len(sub)))

# exact test on the pooled three-run Sonnet existence counts (reviewer item:
# twelve events are too few for the logistic contrast)
if cnt3:
    from scipy.stats import fisher_exact
    a, b = cnt3.get(("baseline", "not_found"), 0), cnt3.get(("baseline", "exists"), 0)
    c_, d = cnt3.get(("combo", "not_found"), 0), cnt3.get(("combo", "exists"), 0)
    emit2("sonnetRunsFisherP", f"{fisher_exact([[a, b], [c_, d]])[1]:.2f}")

with open(OUT, "a") as fh:
    fh.write("\n".join(extra) + "\n")
print(f"+{len(extra)} revision macros")
