#!/usr/bin/env python3
"""Emit docs/jurix/numbers.tex: one \\newcommand per number the paper
cites, computed from the results files. The LaTeX source uses the macros
and never contains a typed number, so a re-score changes the paper by
re-running this script. Macro names are letters only (LaTeX rule)."""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
R = HERE / "results"
OUT = HERE / "docs" / "jurix" / "numbers.tex"

full = json.loads((R / "rescore_full.json").read_text())
loops = json.loads((R / "rescore_loops.json").read_text())
gee = json.loads((R / "stats_gee.json").read_text())
human = json.loads((R / "human_baseline.json").read_text())["aggregates"]["overall"]
pins = json.loads((R / "pincites.json").read_text())
decomp = json.loads((R / "notincorpus_decomposition.json").read_text())

ALPHA = {"qwen30b": "Qwen", "mistralsmall": "Mistral", "llama4mav": "Llama",
         "deepseek": "Deepseek", "gpt54mini": "Gpt", "sonnet": "Sonnet"}
CONDS = {"baseline": "Base", "quota": "Quota", "temporal": "Temporal",
         "stakes": "Stakes", "combo": "Combo"}

lines = ["% generated by src/emit_macros.py; do not edit by hand"]


def emit(name, value):
    lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")


def fmt3(x):
    return f"{x:.3f}"


for m, mk in ALPHA.items():
    for c, ck in CONDS.items():
        cell = full[m][c]
        emit(f"exist{mk}{ck}", fmt3(cell["existence_rate"]))
        emit(f"strict{mk}{ck}", fmt3(cell["strict_rate"]))
        if cell["tchecked"]:
            emit(f"viol{mk}{ck}", f"{100 * cell['viol'] / cell['tchecked']:.0f}")
    for arm, ak in (("true", "True"), ("scrambled", "Scr"), ("none", "None"), ("half", "Half")):
        sub = [r for r in loops[m] if r["arm"] == arm]
        if not sub:
            continue
        f0 = [r["r0"]["strict"] for r in sub if r["r0"]["strict"] is not None]
        f1 = [r["final"]["strict"] for r in sub if r["final"]["strict"] is not None]
        emit(f"loop{mk}{ak}Start", fmt3(sum(f0) / len(f0)))
        emit(f"loop{mk}{ak}Final", fmt3(sum(f1) / len(f1)))
        emit(f"conv{mk}{ak}", str(sum(r["converged"] for r in sub)))
    tr = [r for r in loops[m] if r["arm"] == "true"]
    emit(f"cleanRZero{mk}", str(sum(1 for r in tr if r["converged"] and r["rounds"] == 1)))
    for kind, kk in (("citation", "Cite"), ("quote", "Quote")):
        for c, ck in CONDS.items():
            if c == "baseline":
                continue
            g = gee.get(f"{kind}:{m}:{c}")
            if g:
                emit(f"or{kk}{mk}{ck}", f"{g['OR']:.2f}")
                if "ci_low" in g:
                    emit(f"ci{kk}{mk}{ck}", f"{g['ci_low']:.2f} to {g['ci_high']:.2f}")
                emit(f"p{kk}{mk}{ck}", f"{g['p']:.4f}" if g["p"] >= 0.0001 else "<0.0001")
                emit(f"sig{kk}{mk}{ck}", "*" if g["p"] < 0.05 else "")
    p = pins.get(m)
    if p:
        tot = p["quote_at_pin"] + p["quote_near_pin"] + p["quote_not_at_pin"]
        if tot:
            emit(f"pinAt{mk}", f"{100 * p['quote_at_pin'] / tot:.0f}")
            emit(f"pinWrong{mk}", f"{100 * p['quote_not_at_pin'] / tot:.0f}")

ph = pins.get("human")
if ph:
    tot = ph["quote_at_pin"] + ph["quote_near_pin"] + ph["quote_not_at_pin"]
    emit("pinAtHuman", f"{100 * ph['quote_at_pin'] / tot:.0f}")
    emit("pinHumanN", str(tot))
emit("cleanRZeroTotal", str(sum(1 for m in ALPHA for r in loops[m] if r["arm"] == "true" and r["converged"] and r["rounds"] == 1)))
emit("humanStrict", fmt3(human["strict_quote_rate"]))
emit("humanScored", str(human["n_quotes_scored"]))
emit("humanExist", fmt3(human["existence_rate"]))
emit("humanExcerpts", str(human["n_excerpts"]))
emit("nModels", str(len(ALPHA)))
emit("nDrafts", f"{48 * 5 * len(ALPHA):,}")
emit("nEpisodes", f"{48 * len(ALPHA)}")
emit("sonnetParaphrase", str(decomp["sonnet"]["paraphrase_in_quotes"]))
emit("sonnetFabricated", str(decomp["sonnet"]["fabricated_language"]))
emit("sonnetOutOfScope", str(decomp["sonnet"]["out_of_scope_non_us"]))
s = decomp["sonnet"]
emit("sonnetParaphrasePct",
     f"{100 * s['paraphrase_in_quotes'] / (s['paraphrase_in_quotes'] + s['fabricated_language'] + s['out_of_scope_non_us']):.0f}")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"{len(lines) - 1} macros -> {OUT}")

# ---- revision additions (all optional: skip if the artifact is absent) ----
extra = []


def emit2(name, value):
    extra.append(f"\\newcommand{{\\{name}}}{{{value}}}")


rs_path = R / "revision_stats.json"
if rs_path.exists():
    rs = json.loads(rs_path.read_text())
    emit2("nPressured", f"{rs['n_pressured_drafts']:,}")
    emit2("nHolmTests", str(next(iter(rs["holm"].values()))["n_tests"]))
    emit2("humanLenient", f"{rs['human_lenient']:.3f}")
    emit2("humanNearMissShare", f"{100 * rs['human_near_miss_share']:.0f}")
    for key, v in rs["holm"].items():
        kind, m, c = key.split(":")
        mk = ALPHA.get(m)
        if mk:
            kk = "Cite" if kind == "citation" else "Quote"
            emit2(f"holm{kk}{mk}{CONDS[c]}", f"{v['holm_p']:.3f}" if v["holm_p"] >= 0.001 else "<0.001")
    for cell, v in rs["cells"].items():
        m, c = cell.split(":")
        mk = ALPHA.get(m)
        if mk and v.get("lenient") is not None:
            emit2(f"lenient{mk}{CONDS[c]}", f"{v['lenient']:.3f}")
    for key, v in rs["loop_counts"].items():
        m, arm = key.split(":")
        mk = ALPHA.get(m)
        ak = {"true": "True", "scrambled": "Scr", "none": "None", "half": "Half"}.get(arm)
        if mk and ak:
            emit2(f"lqScored{mk}{ak}Start", str(v["quotes_scored_r0"]))
            emit2(f"lqScored{mk}{ak}Final", str(v["quotes_scored_final"]))
            emit2(f"lqAcc{mk}{ak}Start", str(v["accurate_r0"]))
            emit2(f"lqAcc{mk}{ak}Final", str(v["accurate_final"]))
            emit2(f"lCites{mk}{ak}Start", str(v["cites_r0"]))
            emit2(f"lCites{mk}{ak}Final", str(v["cites_final"]))
            if v.get("exist_r0") == v.get("exist_r0"):
                emit2(f"lExist{mk}{ak}Start", fmt3(v["exist_r0"]))
                emit2(f"lExist{mk}{ak}Final", fmt3(v["exist_final"]))
    for key, v in rs.get("loop_tests", {}).items():
        m, contrast = key.split(":")
        mk = ALPHA.get(m)
        ck = {"true_vs_scrambled": "Scr", "true_vs_none": "None", "true_vs_half": "Half"}[contrast]
        if mk:
            emit2(f"ldiff{mk}{ck}", f"{v['mean_diff']:.2f}")
            emit2(f"lci{mk}{ck}", f"{v['ci_low']:.2f} to {v['ci_high']:.2f}")
            emit2(f"lp{mk}{ck}", f"{v['wilcoxon_p']:.3f}" if v["wilcoxon_p"] >= 0.001 else f"{v['wilcoxon_p']:.4f}")
            emit2(f"ln{mk}{ck}", str(v["n_pairs"]))
    emit2("unverifiablePct", f"{rs['unverifiable_share_pct']:.1f}")
    emit2("nCitationRecords", f"{rs['n_citation_records']:,}")
    emit2("sonnetTempChecked", str(rs["sonnet_temporal_checked"]))
    emit2("sonnetTempViol", str(rs["sonnet_temporal_viol"]))
    gm = rs["glm_missing"]
    emit2("glmMissing", str(sum(gm.values())))
    emit2("glmMissingCombo", str(gm["combo"]))
    for key, v in rs["memorization"].items():
        m, c = key.split(":")
        mk = ALPHA.get(m)
        if mk and v["canonical_share"] is not None:
            emit2(f"canon{mk}{CONDS[c]}", f"{100 * v['canonical_share']:.0f}")
    raw = rs["raw_counts"]
    for m, mk in ALPHA.items():
        for c, ck in CONDS.items():
            d = raw.get(f"{m}:{c}:citation", {})
            emit2(f"nf{mk}{ck}", str(d.get("not_found", 0)))
            emit2(f"ex{mk}{ck}", str(d.get("exists", 0)))

pp = R / "paraphrase_comparison.json"
if pp.exists():
    para = json.loads(pp.read_text())
    for m, mk in ALPHA.items():
        if m in para:
            for which, wk in (("original", "Orig"), ("paraphrase", "Para")):
                c = para[m][which].get("combo", {})
                if c.get("exist") is not None:
                    emit2(f"para{wk}Exist{mk}Combo", fmt3(c["exist"]))
                if c.get("strict") is not None:
                    emit2(f"para{wk}Strict{mk}Combo", fmt3(c["strict"]))

gl = R / "full_glm47flash" / "drafts"
if gl.exists():
    emit2("glmDrafts", str(len(list(gl.glob("*.txt")))))

dc = R / "notincorpus_decomposition.json"
if dc.exists():
    d = json.loads(dc.read_text())
    for m, mk in ALPHA.items():
        if m in d:
            x = d[m]
            tot = x["paraphrase_in_quotes"] + x["fabricated_language"] + x["out_of_scope_non_us"]
            emit2(f"decompPara{mk}", str(x["paraphrase_in_quotes"]))
            emit2(f"decompFab{mk}", str(x["fabricated_language"]))
            emit2(f"decompOut{mk}", str(x["out_of_scope_non_us"]))
            if tot:
                emit2(f"decompParaPct{mk}", f"{100 * x['paraphrase_in_quotes'] / tot:.0f}")

pr = R / "provenance_report.md"
if pr.exists():
    import re as _re
    from collections import Counter as _C
    cnt = _C()
    for line in open(pr):
        m_ = _re.match(r"- \*\*(\w+)\*\* \| (\w+) ", line)
        if m_:
            cnt[(m_.group(2), m_.group(1))] += 1
    for m, mk in ALPHA.items():
        if any(k[0] == m for k in cnt):
            emit2(f"misattr{mk}", str(cnt[(m, "misattributed")]))
            emit2(f"falseAlarm{mk}", str(cnt[(m, "found_in_attributed")]))
            emit2(f"notInCorpus{mk}", str(cnt[(m, "not_in_scotus_corpus")]))
    emit2("misattrTotal", str(sum(v for k, v in cnt.items() if k[1] == "misattributed")))
    for m, mk in ALPHA.items():
        tot = sum(v for k, v in cnt.items() if k[0] == m)
        if tot:
            emit2(f"inaccTotal{mk}", str(tot))
            emit2(f"falseAlarmPct{mk}", f"{100 * cnt[(m, 'found_in_attributed')] / tot:.1f}")

rp = R / "replicate.json"
if rp.exists():
    rep = json.loads(rp.read_text())
    diffs_e, diffs_s, ident = [], [], []
    for m, mk in ALPHA.items():
        if m not in rep:
            continue
        r = rep[m]
        for c, ck in (("baseline", "Base"), ("combo", "Combo")):
            for run, rk in (("run1", "One"), ("run2", "Two")):
                emit2(f"rep{rk}Exist{mk}{ck}", fmt3(r[c][run]["exist"]))
                if r[c][run]["strict"] is not None:
                    emit2(f"rep{rk}Strict{mk}{ck}", fmt3(r[c][run]["strict"]))
            diffs_e.append(abs(r[c]["run1"]["exist"] - r[c]["run2"]["exist"]))
            if None not in (r[c]["run1"]["strict"], r[c]["run2"]["strict"]):
                diffs_s.append(abs(r[c]["run1"]["strict"] - r[c]["run2"]["strict"]))
        ident.append(r["identical_drafts"])
    emit2("repMaxExistDiff", fmt3(max(diffs_e)))
    emit2("repMaxStrictDiff", fmt3(max(diffs_s)))
    emit2("repMedianStrictDiff", fmt3(sorted(diffs_s)[len(diffs_s) // 2]))
    emit2("repIdentical", str(sum(int(x.split("/")[0]) for x in ident)))
    emit2("repDrafts", str(sum(int(x.split("/")[1]) for x in ident)))
    emit2("repModels", str(len(ident)))

lt = R / "loop_transitions.json"
if lt.exists():
    t = json.loads(lt.read_text())
    for m, mk in ALPHA.items():
        if m not in t:
            continue
        c = t[m]
        for arm, ak in (("true", "True"), ("scrambled", "Scr"), ("none", "None"), ("half", "Half")):
            for v0, vk in (("flagged", "Flag"), ("accurate", "Acc")):
                kept_acc = c.get(f"{arm}:{v0}:kept:accurate", 0) + c.get(f"{arm}:{v0}:edited:accurate", 0)
                kept_flag = c.get(f"{arm}:{v0}:kept:flagged", 0) + c.get(f"{arm}:{v0}:edited:flagged", 0)
                emit2(f"tr{ak}{vk}ToAcc{mk}", str(kept_acc))
                emit2(f"tr{ak}{vk}ToFlag{mk}", str(kept_flag))
                emit2(f"tr{ak}{vk}Dequoted{mk}", str(c.get(f"{arm}:{v0}:dequoted", 0)))
                emit2(f"tr{ak}{vk}Deleted{mk}", str(c.get(f"{arm}:{v0}:deleted", 0)))
            emit2(f"tr{ak}AddedAcc{mk}", str(c.get(f"{arm}:added:accurate", 0)))
            emit2(f"tr{ak}AddedFlag{mk}", str(c.get(f"{arm}:added:flagged", 0)))
            fl = [c.get(f"{arm}:flagged:{k}", 0) for k in
                  ("kept:flagged", "edited:flagged", "kept:accurate", "edited:accurate", "dequoted", "deleted")]
            ac = [c.get(f"{arm}:accurate:{k}", 0) for k in
                  ("kept:accurate", "edited:accurate", "kept:flagged", "edited:flagged", "dequoted", "deleted")]
            if arm == "true":
                emit2(f"trFlagRZero{mk}", str(sum(fl)))
                emit2(f"trAccRZero{mk}", str(sum(ac)))
            emit2(f"tr{ak}AccRemoved{mk}", str(ac[2] + ac[3] + ac[4] + ac[5]))
            emit2(f"tr{ak}FlagRemoved{mk}", str(fl[4] + fl[5]))

with open(OUT, "a") as fh:
    fh.write("\n".join(extra) + "\n")
print(f"+{len(extra)} revision macros")
