#!/usr/bin/env python3
"""Emit docs/jurix/numbers.tex: one \\newcommand per number the paper
cites, computed from the results files. The LaTeX source uses the macros
and never contains a typed number, so a re-score changes the paper by
re-running this script. Macro names are letters only (LaTeX rule)."""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
R = HERE / "results"
OUT = HERE / "docs" / "jurix" / "numbers.tex"

full = json.loads((R / "rescore_full.json").read_text())
loops = json.loads((R / "rescore_loops.json").read_text())
gee = json.loads((R / "stats_gee.json").read_text())
human = json.loads((R / "human_baseline.json").read_text())["aggregates"]["overall"]
pins = json.loads((R / "pincites.json").read_text())
decomp = json.loads((R / "notincorpus_decomposition.json").read_text())

ALPHA = {"qwen30b": "Qwen", "mistralsmall": "Mistral", "llama4mav": "Llama",
         "deepseek": "Deepseek", "gpt54mini": "Gpt", "sonnet": "Sonnet"}
CONDS = {"baseline": "Base", "quota": "Quota", "temporal": "Temporal",
         "stakes": "Stakes", "combo": "Combo"}

lines = ["% generated by src/emit_macros.py; do not edit by hand"]


def emit(name, value):
    lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")


def fmt3(x):
    return f"{x:.3f}"


for m, mk in ALPHA.items():
    for c, ck in CONDS.items():
        cell = full[m][c]
        emit(f"exist{mk}{ck}", fmt3(cell["existence_rate"]))
        emit(f"strict{mk}{ck}", fmt3(cell["strict_rate"]))
        if cell["tchecked"]:
            emit(f"viol{mk}{ck}", f"{100 * cell['viol'] / cell['tchecked']:.0f}")
    for arm, ak in (("true", "True"), ("scrambled", "Scr")):
        sub = [r for r in loops[m] if r["arm"] == arm]
        f0 = [r["r0"]["strict"] for r in sub if r["r0"]["strict"] is not None]
        f1 = [r["final"]["strict"] for r in sub if r["final"]["strict"] is not None]
        emit(f"loop{mk}{ak}Start", fmt3(sum(f0) / len(f0)))
        emit(f"loop{mk}{ak}Final", fmt3(sum(f1) / len(f1)))
        emit(f"conv{mk}{ak}", str(sum(r["converged"] for r in sub)))
    for kind, kk in (("citation", "Cite"), ("quote", "Quote")):
        for c, ck in CONDS.items():
            if c == "baseline":
                continue
            g = gee.get(f"{kind}:{m}:{c}")
            if g:
                emit(f"or{kk}{mk}{ck}", f"{g['OR']:.2f}")
                emit(f"p{kk}{mk}{ck}", f"{g['p']:.4f}" if g["p"] >= 0.0001 else "<0.0001")
                emit(f"sig{kk}{mk}{ck}", "*" if g["p"] < 0.05 else "")
    p = pins.get(m)
    if p:
        tot = p["quote_at_pin"] + p["quote_near_pin"] + p["quote_not_at_pin"]
        if tot:
            emit(f"pinAt{mk}", f"{100 * p['quote_at_pin'] / tot:.0f}")
            emit(f"pinWrong{mk}", f"{100 * p['quote_not_at_pin'] / tot:.0f}")

emit("humanStrict", fmt3(human["strict_quote_rate"]))
emit("humanScored", str(human["n_quotes_scored"]))
emit("humanExist", fmt3(human["existence_rate"]))
emit("humanExcerpts", str(human["n_excerpts"]))
emit("nModels", str(len(ALPHA)))
emit("nDrafts", f"{48 * 5 * len(ALPHA):,}")
emit("nEpisodes", f"{48 * len(ALPHA)}")
emit("sonnetParaphrase", str(decomp["sonnet"]["paraphrase_in_quotes"]))
emit("sonnetFabricated", str(decomp["sonnet"]["fabricated_language"]))
emit("sonnetOutOfScope", str(decomp["sonnet"]["out_of_scope_non_us"]))
s = decomp["sonnet"]
emit("sonnetParaphrasePct",
     f"{100 * s['paraphrase_in_quotes'] / (s['paraphrase_in_quotes'] + s['fabricated_language'] + s['out_of_scope_non_us']):.0f}")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"{len(lines) - 1} macros -> {OUT}")
